/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Movie;
import io.swagger.model.ResponseError;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-10-02T14:53:20.805Z")

@Api(value = "movies", description = "the movies API")
public interface MoviesApi {

    @ApiOperation(value = "Cadastra um novo filme", nickname = "addMovie", notes = "", response = Object.class, tags={ "movies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Filme criado com sucesso", response = Object.class),
        @ApiResponse(code = 400, message = "Parâmetros invalidos - client side", response = ResponseError.class),
        @ApiResponse(code = 500, message = "Erro durante a criação - server side", response = ResponseError.class) })
    @RequestMapping(value = "/movies",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Object> addMovie(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Movie movie);


    @ApiOperation(value = "Detalhe de filme", nickname = "getMovie", notes = "", response = Object.class, tags={ "movies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Filme consultado com sucesso", response = Object.class),
        @ApiResponse(code = 400, message = "Parâmetros invalidos - client side", response = ResponseError.class),
        @ApiResponse(code = 500, message = "Erro durante a consulta - server side", response = ResponseError.class) })
    @RequestMapping(value = "/movies/{movieId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> getMovie(@ApiParam(value = "",required=true) @PathVariable("movieId") Long movieId);


    @ApiOperation(value = "Lista os filmes cinematográficos", nickname = "listMovies", notes = "", response = Object.class, tags={ "movies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Filmes consultados com sucesso", response = Object.class),
        @ApiResponse(code = 400, message = "Parâmetros invalidos - client side", response = ResponseError.class),
        @ApiResponse(code = 500, message = "Erro durante a criação - server side", response = ResponseError.class) })
    @RequestMapping(value = "/movies",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> listMovies(@ApiParam(value = "Página da listagem a ser retornada", defaultValue = "1") @Valid @RequestParam(value = "page", required = false, defaultValue="1") Integer page,@ApiParam(value = "Tamanho da paginação a ser utilizada no request", defaultValue = "10") @Valid @RequestParam(value = "size", required = false, defaultValue="10") Integer size,@ApiParam(value = "Retorna itens cuja descrição se pareça com o valor informado") @Valid @RequestParam(value = "search", required = false) String search);


    @ApiOperation(value = "Remove um filme do catálogo", nickname = "removeMovie", notes = "", tags={ "movies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Filme removido com sucesso"),
        @ApiResponse(code = 404, message = "Filme não encontrado", response = ResponseError.class),
        @ApiResponse(code = 500, message = "Erro durante a deleção - server side", response = ResponseError.class) })
    @RequestMapping(value = "/movies/{movieId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> removeMovie(@ApiParam(value = "",required=true) @PathVariable("movieId") Long movieId);


    @ApiOperation(value = "Atualização de filme", nickname = "updateMovie", notes = "", response = Object.class, tags={ "movies", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Filme atualizado com sucesso", response = Object.class),
        @ApiResponse(code = 400, message = "Parâmetros invalidos - client side", response = ResponseError.class),
        @ApiResponse(code = 500, message = "Erro durante a criação - server side", response = ResponseError.class) })
    @RequestMapping(value = "/movies/{movieId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Object> updateMovie(@ApiParam(value = "",required=true) @PathVariable("movieId") Long movieId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Movie movie);

}
