version: '3'
services:
  db:
    image: mysql/mysql-server:8.0.17
    environment:
      - MYSQL_DATABASE=movies_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    restart: always
    networks:
      - network-db
  spring-boot:
    image: api-spring
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: spring-boot-api
    expose:
      - 5000
    restart: always
    networks:
      - network-db
    depends_on:
      - db
networks:
    network-db:
      driver: bridge